import { useState, useRef } from 'react';
import { Sparkles, LayoutGrid, CreditCard, HelpCircle, MousePointerClick, Mail, PanelBottom, Trash2, Copy, Eye, Pencil, Monitor, Tablet, Smartphone, Download, ChevronDown, Check, Image, Video, Quote, Users, BarChart3, Clock, Palette, Plus, X, Layers, Zap, Shield, Heart, Star, Target, TrendingUp, Award, ChevronRight, Minus, Move, Upload, FolderOpen, ChevronUp } from 'lucide-react';

type SectionType = 'hero' | 'features' | 'pricing' | 'testimonials' | 'stats' | 'video' | 'gallery' | 'logos' | 'faq' | 'cta' | 'contact' | 'footer' | 'divider' | 'spacer';
interface SectionStyles { backgroundColor: string; textColor: string; padding: string; backgroundType: string; gradientFrom: string; gradientTo: string; gradientDirection: string; backgroundImage: string; }
interface Section { id: string; type: SectionType; content: any; styles: SectionStyles; }

const iconLibrary: Record<string, any> = { Zap, Shield, Heart, Star, Target, TrendingUp, Award, Users, BarChart3, Clock, Sparkles, Check, Mail, CreditCard };

const ImageUploader = ({ value, onChange, label = "画像" }: { value: string; onChange: (v: string) => void; label?: string }) => {
  const inputRef = useRef<HTMLInputElement>(null);
  const [isDragging, setIsDragging] = useState(false);
  const handleFile = (file: File) => { if (file?.type.startsWith('image/')) { const r = new FileReader(); r.onload = (e) => onChange(e.target?.result as string); r.readAsDataURL(file); } };
  return (
    <div style={{ marginBottom: '1rem' }}>
      <label style={{ display: 'block', color: '#9ca3af', fontSize: '0.75rem', marginBottom: '0.5rem', textTransform: 'uppercase' }}>{label}</label>
      <div onClick={() => inputRef.current?.click()} onDrop={(e) => { e.preventDefault(); setIsDragging(false); handleFile(e.dataTransfer.files[0]); }} onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }} onDragLeave={() => setIsDragging(false)} style={{ border: `2px dashed ${isDragging ? '#0ea5e9' : '#4b5563'}`, borderRadius: '0.5rem', padding: '1rem', textAlign: 'center', cursor: 'pointer', backgroundColor: isDragging ? 'rgba(14,165,233,0.1)' : 'transparent' }}>
        {value ? (<div style={{ position: 'relative' }}><img src={value} alt="Preview" style={{ maxWidth: '100%', maxHeight: '100px', borderRadius: '0.375rem', objectFit: 'cover' }} /><button onClick={(e) => { e.stopPropagation(); onChange(''); }} style={{ position: 'absolute', top: '-8px', right: '-8px', width: '20px', height: '20px', borderRadius: '50%', backgroundColor: '#ef4444', color: 'white', border: 'none', cursor: 'pointer', fontSize: '12px' }}>×</button></div>) : (<div style={{ color: '#6b7280' }}><Upload size={20} style={{ margin: '0 auto 0.5rem' }} /><p style={{ fontSize: '0.75rem' }}>ドラッグ&ドロップ</p></div>)}
      </div>
      <input ref={inputRef} type="file" accept="image/*" onChange={(e) => e.target.files && handleFile(e.target.files[0])} style={{ display: 'none' }} />
      <input type="text" value={typeof value === 'string' && !value.startsWith('data:') ? value : ''} onChange={(e) => onChange(e.target.value)} placeholder="または画像URLを入力" style={{ width: '100%', marginTop: '0.5rem', padding: '0.5rem', backgroundColor: '#313244', border: 'none', borderRadius: '0.375rem', color: 'white', fontSize: '0.75rem', boxSizing: 'border-box' }} />
    </div>
  );
};

const getDefaultContent = (type: SectionType): any => {
  const d: Record<SectionType, any> = {
    hero: { title: 'あなたのビジネスを\n次のレベルへ', subtitle: 'シンプルで使いやすいサービスで成長をサポート', ctaText: '今すぐ始める', ctaLink: '#contact', secondaryCtaText: '詳しく見る', secondaryCtaLink: '#features', backgroundImage: '', overlay: true, overlayOpacity: 0.5 },
    features: { title: '主な特徴', subtitle: '選ばれる理由', features: [{ id: '1', icon: 'Zap', title: '高速', description: '驚くほど高速' }, { id: '2', icon: 'Shield', title: '安全', description: '最高のセキュリティ' }, { id: '3', icon: 'Heart', title: '使いやすい', description: '直感的なUI' }] },
    pricing: { title: '料金プラン', subtitle: '最適なプランを', plans: [{ id: '1', name: 'スターター', price: '無料', period: '', description: '個人向け', features: ['基本機能', 'メールサポート'], ctaText: '無料で始める', isPopular: false }, { id: '2', name: 'プロ', price: '¥2,980', period: '/月', description: 'チーム向け', features: ['全機能', '優先サポート', 'API'], ctaText: '14日間無料', isPopular: true }, { id: '3', name: 'エンタープライズ', price: 'お問い合わせ', period: '', description: '大規模向け', features: ['カスタム', '専任サポート'], ctaText: 'お問い合わせ', isPopular: false }] },
    testimonials: { title: 'お客様の声', testimonials: [{ id: '1', name: '田中太郎', role: 'CEO', company: '株式会社サンプル', content: '業務効率が大幅に向上しました。', avatar: '', rating: 5 }, { id: '2', name: '鈴木花子', role: 'マーケター', company: 'テック株式会社', content: '素晴らしいバランスです。', avatar: '', rating: 5 }] },
    stats: { title: '', stats: [{ id: '1', value: '10,000+', label: 'ユーザー' }, { id: '2', value: '99.9%', label: '稼働率' }, { id: '3', value: '50+', label: '導入企業' }, { id: '4', value: '24/7', label: 'サポート' }] },
    video: { title: 'サービス紹介', videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ' },
    gallery: { title: 'ギャラリー', images: [{ id: '1', url: '', caption: '画像1' }, { id: '2', url: '', caption: '画像2' }, { id: '3', url: '', caption: '画像3' }], columns: 3 },
    logos: { title: '導入企業', logos: [{ id: '1', name: 'Company A', url: '' }, { id: '2', name: 'Company B', url: '' }, { id: '3', name: 'Company C', url: '' }, { id: '4', name: 'Company D', url: '' }] },
    faq: { title: 'よくある質問', items: [{ id: '1', question: '無料で使えますか？', answer: '基本機能は無料です。' }, { id: '2', question: '解約できますか？', answer: 'いつでも可能です。' }] },
    cta: { title: '今すぐ始めましょう', subtitle: '無料で始められます', buttonText: '無料で始める', buttonLink: '#', secondaryText: 'お問い合わせ', secondaryLink: '#contact' },
    contact: { title: 'お問い合わせ', subtitle: 'お気軽にどうぞ', fields: [{ id: '1', type: 'text', label: 'お名前', placeholder: '山田太郎', required: true }, { id: '2', type: 'email', label: 'メール', placeholder: 'example@email.com', required: true }, { id: '3', type: 'textarea', label: 'メッセージ', placeholder: '内容', required: true }], submitText: '送信' },
    footer: { companyName: 'Your Company', description: 'ビジネスをサポート', links: [{ id: '1', title: 'サービス', items: [{ label: '機能', url: '#' }, { label: '料金', url: '#' }] }], copyright: '© 2026 Your Company' },
    divider: { color: '#e5e7eb' },
    spacer: { height: 60 }
  };
  return d[type];
};

const getDefaultStyles = (type: SectionType): SectionStyles => ({ backgroundColor: ['cta', 'hero', 'footer', 'stats'].includes(type) ? (type === 'cta' ? '#0ea5e9' : '#0f172a') : '#ffffff', textColor: ['cta', 'hero', 'footer', 'stats'].includes(type) ? '#ffffff' : '#1f2937', padding: type === 'hero' ? 'xlarge' : ['spacer', 'divider'].includes(type) ? 'none' : 'large', backgroundType: 'solid', gradientFrom: '#0ea5e9', gradientTo: '#8b5cf6', gradientDirection: 'to right', backgroundImage: '' });

const sectionMeta: Record<SectionType, { label: string; Icon: any }> = { hero: { label: 'ヒーロー', Icon: Sparkles }, features: { label: '特徴', Icon: LayoutGrid }, pricing: { label: '料金', Icon: CreditCard }, testimonials: { label: 'お客様の声', Icon: Quote }, stats: { label: '実績', Icon: BarChart3 }, video: { label: '動画', Icon: Video }, gallery: { label: 'ギャラリー', Icon: Image }, logos: { label: 'ロゴ', Icon: Layers }, faq: { label: 'FAQ', Icon: HelpCircle }, cta: { label: 'CTA', Icon: MousePointerClick }, contact: { label: 'お問い合わせ', Icon: Mail }, footer: { label: 'フッター', Icon: PanelBottom }, divider: { label: '区切り', Icon: Minus }, spacer: { label: 'スペース', Icon: Move } };

const templates: Record<string, { name: string; desc: string; Icon: any; sections: Omit<Section, 'id'>[] }> = {
  blank: { name: '空白', desc: 'ゼロから', Icon: Plus, sections: [] },
  saas: { name: 'SaaS', desc: 'ソフトウェア向け', Icon: Sparkles, sections: [{ type: 'hero', content: { ...getDefaultContent('hero'), title: '業務効率を10倍に' }, styles: { ...getDefaultStyles('hero'), backgroundType: 'gradient', gradientFrom: '#0f172a', gradientTo: '#1e3a5f' } }, { type: 'logos', content: getDefaultContent('logos'), styles: { ...getDefaultStyles('logos'), backgroundColor: '#f8fafc', padding: 'medium' } }, { type: 'features', content: getDefaultContent('features'), styles: getDefaultStyles('features') }, { type: 'stats', content: getDefaultContent('stats'), styles: { ...getDefaultStyles('stats'), backgroundType: 'gradient', gradientFrom: '#0ea5e9', gradientTo: '#8b5cf6' } }, { type: 'pricing', content: getDefaultContent('pricing'), styles: getDefaultStyles('pricing') }, { type: 'testimonials', content: getDefaultContent('testimonials'), styles: { ...getDefaultStyles('testimonials'), backgroundColor: '#f8fafc' } }, { type: 'faq', content: getDefaultContent('faq'), styles: getDefaultStyles('faq') }, { type: 'cta', content: getDefaultContent('cta'), styles: { ...getDefaultStyles('cta'), backgroundType: 'gradient', gradientFrom: '#0ea5e9', gradientTo: '#8b5cf6' } }, { type: 'footer', content: getDefaultContent('footer'), styles: getDefaultStyles('footer') }] },
  coaching: { name: 'コーチング', desc: '個人サービス', Icon: Users, sections: [{ type: 'hero', content: { ...getDefaultContent('hero'), title: 'あなたの可能性を\n最大限に', ctaText: '無料相談' }, styles: { ...getDefaultStyles('hero'), backgroundType: 'gradient', gradientFrom: '#1e3a5f', gradientTo: '#0f172a' } }, { type: 'stats', content: { ...getDefaultContent('stats'), stats: [{ id: '1', value: '500+', label: 'クライアント' }, { id: '2', value: '95%', label: '達成率' }, { id: '3', value: '10年', label: '経験' }] }, styles: { ...getDefaultStyles('stats'), backgroundColor: '#ffffff', textColor: '#1f2937' } }, { type: 'features', content: { ...getDefaultContent('features'), title: 'サービス' }, styles: getDefaultStyles('features') }, { type: 'testimonials', content: getDefaultContent('testimonials'), styles: { ...getDefaultStyles('testimonials'), backgroundColor: '#f8fafc' } }, { type: 'pricing', content: { ...getDefaultContent('pricing'), title: 'コース' }, styles: getDefaultStyles('pricing') }, { type: 'cta', content: { ...getDefaultContent('cta'), title: '無料相談から' }, styles: getDefaultStyles('cta') }, { type: 'footer', content: getDefaultContent('footer'), styles: getDefaultStyles('footer') }] }
};

const DynamicIcon = ({ name, size = 24, style = {} }: { name: string; size?: number; style?: React.CSSProperties }) => { const I = iconLibrary[name] || Sparkles; return <I size={size} style={style} />; };

const HeroSection = ({ content, styles, isPreview, onUpdate }: any) => {
  const bgStyle: React.CSSProperties = styles.backgroundType === 'gradient' ? { background: `linear-gradient(${styles.gradientDirection}, ${styles.gradientFrom}, ${styles.gradientTo})` } : styles.backgroundType === 'image' && (content.backgroundImage || styles.backgroundImage) ? { backgroundImage: `url(${content.backgroundImage || styles.backgroundImage})`, backgroundSize: 'cover', backgroundPosition: 'center' } : {};
  return (
    <div style={{ position: 'relative', minHeight: '550px', display: 'flex', alignItems: 'center', justifyContent: 'center', ...bgStyle }}>
      {content.overlay && <div style={{ position: 'absolute', inset: 0, backgroundColor: `rgba(0,0,0,${content.overlayOpacity})` }} />}
      <div style={{ position: 'relative', zIndex: 10, maxWidth: '64rem', margin: '0 auto', textAlign: 'center', padding: '2rem' }}>
        <h1 style={{ fontSize: 'clamp(2.5rem, 6vw, 4rem)', fontWeight: 'bold', marginBottom: '1.5rem', lineHeight: 1.1, whiteSpace: 'pre-line' }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => onUpdate({ ...content, title: e.currentTarget.textContent })}>{content.title}</h1>
        <p style={{ fontSize: 'clamp(1rem, 2vw, 1.5rem)', opacity: 0.9, marginBottom: '2.5rem', maxWidth: '600px', margin: '0 auto 2.5rem' }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => onUpdate({ ...content, subtitle: e.currentTarget.textContent })}>{content.subtitle}</p>
        <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap', justifyContent: 'center' }}>
          <a href={content.ctaLink} style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '1rem 2rem', backgroundColor: '#0ea5e9', color: 'white', borderRadius: '0.5rem', fontSize: '1.125rem', fontWeight: 600, textDecoration: 'none' }}>{content.ctaText} <ChevronRight size={20} /></a>
          {content.secondaryCtaText && <a href={content.secondaryCtaLink} style={{ display: 'inline-flex', alignItems: 'center', padding: '1rem 2rem', backgroundColor: 'rgba(255,255,255,0.1)', color: 'inherit', border: '2px solid currentColor', borderRadius: '0.5rem', fontWeight: 600, textDecoration: 'none' }}>{content.secondaryCtaText}</a>}
        </div>
      </div>
    </div>
  );
};

const FeaturesSection = ({ content, styles, isPreview, onUpdate }: any) => {
  const updateFeature = (id: string, u: any) => onUpdate({ ...content, features: content.features.map((f: any) => f.id === id ? { ...f, ...u } : f) });
  const addFeature = () => onUpdate({ ...content, features: [...content.features, { id: Date.now().toString(), icon: 'Star', title: '新機能', description: '説明' }] });
  const removeFeature = (id: string) => onUpdate({ ...content, features: content.features.filter((f: any) => f.id !== id) });
  return (
    <div style={{ maxWidth: '72rem', margin: '0 auto' }}>
      <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
        <h2 style={{ fontSize: '2.5rem', fontWeight: 'bold', marginBottom: '1rem' }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => onUpdate({ ...content, title: e.currentTarget.textContent })}>{content.title}</h2>
        <p style={{ opacity: 0.7, maxWidth: '600px', margin: '0 auto' }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => onUpdate({ ...content, subtitle: e.currentTarget.textContent })}>{content.subtitle}</p>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '2rem' }}>
        {content.features.map((f: any) => (
          <div key={f.id} style={{ position: 'relative', textAlign: 'center', padding: '2rem', borderRadius: '1rem', backgroundColor: 'rgba(14,165,233,0.05)' }}>
            {!isPreview && <button onClick={() => removeFeature(f.id)} style={{ position: 'absolute', top: '0.5rem', right: '0.5rem', background: 'none', border: 'none', cursor: 'pointer', opacity: 0.5 }}><X size={14} /></button>}
            <div style={{ width: '4rem', height: '4rem', margin: '0 auto 1.5rem', background: 'linear-gradient(135deg, #0ea5e9, #8b5cf6)', borderRadius: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white' }}><DynamicIcon name={f.icon} size={28} /></div>
            <h3 style={{ fontSize: '1.25rem', fontWeight: 600, marginBottom: '0.75rem' }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => updateFeature(f.id, { title: e.currentTarget.textContent })}>{f.title}</h3>
            <p style={{ opacity: 0.7, lineHeight: 1.6 }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => updateFeature(f.id, { description: e.currentTarget.textContent })}>{f.description}</p>
          </div>
        ))}
      </div>
      {!isPreview && <div style={{ textAlign: 'center', marginTop: '2rem' }}><button onClick={addFeature} style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.75rem 1.5rem', border: '2px dashed #d1d5db', borderRadius: '0.5rem', background: 'none', cursor: 'pointer', color: '#6b7280' }}><Plus size={18} /> 追加</button></div>}
    </div>
  );
};

const StatsSection = ({ content, isPreview, onUpdate }: any) => {
  const updateStat = (id: string, u: any) => onUpdate({ ...content, stats: content.stats.map((s: any) => s.id === id ? { ...s, ...u } : s) });
  return (<div style={{ maxWidth: '72rem', margin: '0 auto' }}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '2rem' }}>{content.stats.map((s: any) => (<div key={s.id} style={{ textAlign: 'center', padding: '1.5rem' }}><div style={{ fontSize: '3rem', fontWeight: 'bold', marginBottom: '0.5rem', background: 'linear-gradient(135deg, #0ea5e9, #8b5cf6)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => updateStat(s.id, { value: e.currentTarget.textContent })}>{s.value}</div><div style={{ opacity: 0.7 }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => updateStat(s.id, { label: e.currentTarget.textContent })}>{s.label}</div></div>))}</div></div>);
};

const TestimonialsSection = ({ content, styles, isPreview, onUpdate }: any) => {
  const updateT = (id: string, u: any) => onUpdate({ ...content, testimonials: content.testimonials.map((t: any) => t.id === id ? { ...t, ...u } : t) });
  return (<div style={{ maxWidth: '72rem', margin: '0 auto' }}><div style={{ textAlign: 'center', marginBottom: '3rem' }}><h2 style={{ fontSize: '2.5rem', fontWeight: 'bold' }}>{content.title}</h2></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '2rem' }}>{content.testimonials.map((t: any) => (<div key={t.id} style={{ backgroundColor: styles.backgroundColor === '#ffffff' ? '#f8fafc' : 'rgba(255,255,255,0.05)', padding: '2rem', borderRadius: '1rem' }}><div style={{ display: 'flex', gap: '0.25rem', marginBottom: '1rem' }}>{[...Array(5)].map((_, i) => <Star key={i} size={16} fill={i < t.rating ? '#fbbf24' : 'none'} color={i < t.rating ? '#fbbf24' : '#d1d5db'} />)}</div><p style={{ fontSize: '1.125rem', lineHeight: 1.7, marginBottom: '1.5rem' }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => updateT(t.id, { content: e.currentTarget.textContent })}>{t.content}</p><div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}><div style={{ width: '3rem', height: '3rem', borderRadius: '50%', backgroundColor: '#0ea5e9', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white', fontWeight: 'bold' }}>{t.name.charAt(0)}</div><div><div style={{ fontWeight: 600 }}>{t.name}</div><div style={{ fontSize: '0.875rem', opacity: 0.7 }}>{t.role}{t.company && ` / ${t.company}`}</div></div></div></div>))}</div></div>);
};

const VideoSection = ({ content, isPreview, onUpdate }: any) => (<div style={{ maxWidth: '56rem', margin: '0 auto' }}><div style={{ textAlign: 'center', marginBottom: '2rem' }}><h2 style={{ fontSize: '2.5rem', fontWeight: 'bold' }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => onUpdate({ ...content, title: e.currentTarget.textContent })}>{content.title}</h2></div><div style={{ position: 'relative', paddingBottom: '56.25%', borderRadius: '1rem', overflow: 'hidden', boxShadow: '0 25px 50px -12px rgba(0,0,0,0.25)' }}><iframe src={content.videoUrl} style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', border: 'none' }} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div>{!isPreview && <input type="text" value={content.videoUrl} onChange={(e) => onUpdate({ ...content, videoUrl: e.target.value })} placeholder="YouTube URL" style={{ width: '100%', marginTop: '1rem', padding: '0.75rem', border: '1px solid #d1d5db', borderRadius: '0.5rem', boxSizing: 'border-box' }} />}</div>);

const GallerySection = ({ content, isPreview, onUpdate }: any) => {
  const updateImg = (id: string, u: any) => onUpdate({ ...content, images: content.images.map((img: any) => img.id === id ? { ...img, ...u } : img) });
  const addImg = () => onUpdate({ ...content, images: [...content.images, { id: Date.now().toString(), url: '', caption: '新画像' }] });
  return (<div style={{ maxWidth: '72rem', margin: '0 auto' }}>{content.title && <div style={{ textAlign: 'center', marginBottom: '2rem' }}><h2 style={{ fontSize: '2.5rem', fontWeight: 'bold' }}>{content.title}</h2></div>}<div style={{ display: 'grid', gridTemplateColumns: `repeat(${content.columns || 3}, 1fr)`, gap: '1.5rem' }}>{content.images.map((img: any) => (<div key={img.id} style={{ position: 'relative', aspectRatio: '4/3', borderRadius: '0.75rem', overflow: 'hidden', backgroundColor: '#f1f5f9' }}>{img.url ? <img src={img.url} alt={img.caption} style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : <div style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', color: '#94a3b8' }}><Image size={32} /><span style={{ fontSize: '0.875rem', marginTop: '0.5rem' }}>{img.caption}</span></div>}{!isPreview && <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, padding: '0.5rem', backgroundColor: 'rgba(0,0,0,0.7)' }}><input type="text" value={img.url} onChange={(e) => updateImg(img.id, { url: e.target.value })} placeholder="画像URL" style={{ width: '100%', padding: '0.375rem', borderRadius: '0.25rem', border: 'none', fontSize: '0.75rem', boxSizing: 'border-box' }} /></div>}</div>))}</div>{!isPreview && <div style={{ textAlign: 'center', marginTop: '2rem' }}><button onClick={addImg} style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.75rem 1.5rem', border: '2px dashed #d1d5db', borderRadius: '0.5rem', background: 'none', cursor: 'pointer', color: '#6b7280' }}><Plus size={18} /> 追加</button></div>}</div>);
};

const LogosSection = ({ content, styles }: any) => (<div style={{ maxWidth: '72rem', margin: '0 auto' }}>{content.title && <h2 style={{ fontSize: '1.25rem', fontWeight: 600, marginBottom: '2rem', textAlign: 'center', opacity: 0.6 }}>{content.title}</h2>}<div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', alignItems: 'center', gap: '3rem' }}>{content.logos.map((l: any) => <div key={l.id} style={{ padding: '1rem', opacity: 0.5 }}>{l.url ? <img src={l.url} alt={l.name} style={{ height: '40px', objectFit: 'contain' }} /> : <div style={{ padding: '1rem 2rem', backgroundColor: styles.backgroundColor === '#ffffff' ? '#f1f5f9' : 'rgba(255,255,255,0.1)', borderRadius: '0.5rem', fontWeight: 600, color: '#64748b' }}>{l.name}</div>}</div>)}</div></div>);

const PricingSection = ({ content }: any) => (<div style={{ maxWidth: '72rem', margin: '0 auto' }}><div style={{ textAlign: 'center', marginBottom: '3rem' }}><h2 style={{ fontSize: '2.5rem', fontWeight: 'bold', marginBottom: '1rem' }}>{content.title}</h2><p style={{ opacity: 0.7 }}>{content.subtitle}</p></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '2rem', alignItems: 'start' }}>{content.plans.map((p: any) => (<div key={p.id} style={{ padding: '2.5rem', borderRadius: '1.5rem', position: 'relative', background: p.isPopular ? 'linear-gradient(135deg, #0ea5e9, #8b5cf6)' : '#ffffff', color: p.isPopular ? 'white' : 'inherit', boxShadow: p.isPopular ? '0 25px 50px -12px rgba(14,165,233,0.4)' : '0 4px 6px -1px rgba(0,0,0,0.1)', transform: p.isPopular ? 'scale(1.05)' : 'none', border: p.isPopular ? 'none' : '1px solid #e5e7eb' }}>{p.isPopular && <div style={{ position: 'absolute', top: '-12px', left: '50%', transform: 'translateX(-50%)', padding: '0.25rem 1rem', backgroundColor: '#fbbf24', color: '#1f2937', borderRadius: '9999px', fontSize: '0.75rem', fontWeight: 600 }}>人気</div>}<h3 style={{ fontSize: '1.5rem', fontWeight: 'bold', marginBottom: '0.5rem' }}>{p.name}</h3><p style={{ fontSize: '0.875rem', opacity: 0.8, marginBottom: '1.5rem' }}>{p.description}</p><div style={{ marginBottom: '2rem' }}><span style={{ fontSize: '3rem', fontWeight: 'bold' }}>{p.price}</span><span style={{ opacity: 0.7 }}>{p.period}</span></div><ul style={{ listStyle: 'none', padding: 0, marginBottom: '2rem' }}>{p.features.map((f: string, i: number) => <li key={i} style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}><Check size={16} style={{ color: p.isPopular ? 'white' : '#0ea5e9' }} /> {f}</li>)}</ul><button style={{ width: '100%', padding: '1rem', borderRadius: '0.75rem', fontWeight: 600, cursor: 'pointer', border: 'none', backgroundColor: p.isPopular ? 'white' : '#0ea5e9', color: p.isPopular ? '#0ea5e9' : 'white' }}>{p.ctaText}</button></div>))}</div></div>);

const FAQSection = ({ content, isPreview, onUpdate }: any) => {
  const [openIdx, setOpenIdx] = useState<number | null>(0);
  const updateItem = (id: string, u: any) => onUpdate({ ...content, items: content.items.map((item: any) => item.id === id ? { ...item, ...u } : item) });
  const addItem = () => onUpdate({ ...content, items: [...content.items, { id: Date.now().toString(), question: '新しい質問', answer: '回答' }] });
  return (<div style={{ maxWidth: '48rem', margin: '0 auto' }}><div style={{ textAlign: 'center', marginBottom: '3rem' }}><h2 style={{ fontSize: '2.5rem', fontWeight: 'bold' }}>{content.title}</h2></div><div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>{content.items.map((item: any, idx: number) => (<div key={item.id} style={{ border: '1px solid #e5e7eb', borderRadius: '1rem', overflow: 'hidden' }}><button onClick={() => setOpenIdx(openIdx === idx ? null : idx)} style={{ width: '100%', padding: '1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: openIdx === idx ? '#f8fafc' : 'white', border: 'none', cursor: 'pointer', textAlign: 'left' }}><span style={{ fontWeight: 600, fontSize: '1.125rem', color: '#1f2937' }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => { e.stopPropagation(); updateItem(item.id, { question: e.currentTarget.textContent }); }}>{item.question}</span><ChevronDown size={20} style={{ flexShrink: 0, transform: openIdx === idx ? 'rotate(180deg)' : 'none', transition: 'transform 0.3s', color: '#6b7280' }} /></button><div style={{ maxHeight: openIdx === idx ? '300px' : '0', overflow: 'hidden', transition: 'max-height 0.3s' }}><div style={{ padding: '0 1.5rem 1.5rem', color: '#4b5563', lineHeight: 1.7 }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => updateItem(item.id, { answer: e.currentTarget.textContent })}>{item.answer}</div></div></div>))}</div>{!isPreview && <div style={{ textAlign: 'center', marginTop: '2rem' }}><button onClick={addItem} style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.75rem 1.5rem', border: '2px dashed #d1d5db', borderRadius: '0.5rem', background: 'none', cursor: 'pointer', color: '#6b7280' }}><Plus size={18} /> 追加</button></div>}</div>);
};

const CTASection = ({ content, isPreview, onUpdate }: any) => (<div style={{ textAlign: 'center', maxWidth: '48rem', margin: '0 auto' }}><h2 style={{ fontSize: '2.5rem', fontWeight: 'bold', marginBottom: '1rem' }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => onUpdate({ ...content, title: e.currentTarget.textContent })}>{content.title}</h2><p style={{ fontSize: '1.25rem', opacity: 0.9, marginBottom: '2.5rem' }} contentEditable={!isPreview} suppressContentEditableWarning onBlur={(e) => onUpdate({ ...content, subtitle: e.currentTarget.textContent })}>{content.subtitle}</p><div style={{ display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap' }}><a href={content.buttonLink} style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '1rem 2.5rem', backgroundColor: 'white', color: '#0ea5e9', borderRadius: '0.5rem', fontSize: '1.125rem', fontWeight: 600, textDecoration: 'none', boxShadow: '0 4px 14px rgba(0,0,0,0.1)' }}>{content.buttonText} <ChevronRight size={20} /></a>{content.secondaryText && <a href={content.secondaryLink} style={{ display: 'inline-flex', alignItems: 'center', padding: '1rem 2.5rem', backgroundColor: 'transparent', color: 'white', border: '2px solid white', borderRadius: '0.5rem', fontWeight: 600, textDecoration: 'none' }}>{content.secondaryText}</a>}</div></div>);

const ContactSection = ({ content, styles }: any) => (<div style={{ maxWidth: '40rem', margin: '0 auto' }}><div style={{ textAlign: 'center', marginBottom: '3rem' }}><h2 style={{ fontSize: '2.5rem', fontWeight: 'bold', marginBottom: '1rem' }}>{content.title}</h2><p style={{ opacity: 0.7 }}>{content.subtitle}</p></div><form onSubmit={(e) => e.preventDefault()} style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>{content.fields.map((f: any) => (<div key={f.id}><label style={{ display: 'block', fontWeight: 500, marginBottom: '0.5rem' }}>{f.label}{f.required && <span style={{ color: '#ef4444' }}> *</span>}</label>{f.type === 'textarea' ? <textarea placeholder={f.placeholder} rows={4} style={{ width: '100%', padding: '0.875rem', border: '2px solid #e5e7eb', borderRadius: '0.75rem', resize: 'none', boxSizing: 'border-box', backgroundColor: styles.textColor === '#ffffff' ? 'rgba(255,255,255,0.1)' : 'white', color: styles.textColor }} /> : <input type={f.type} placeholder={f.placeholder} style={{ width: '100%', padding: '0.875rem', border: '2px solid #e5e7eb', borderRadius: '0.75rem', boxSizing: 'border-box', backgroundColor: styles.textColor === '#ffffff' ? 'rgba(255,255,255,0.1)' : 'white', color: styles.textColor }} />}</div>))}<button type="submit" style={{ padding: '1rem 2rem', backgroundColor: '#0ea5e9', color: 'white', border: 'none', borderRadius: '0.75rem', fontSize: '1.125rem', fontWeight: 600, cursor: 'pointer' }}>{content.submitText}</button></form></div>);

const FooterSection = ({ content }: any) => (<div style={{ maxWidth: '72rem', margin: '0 auto' }}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '3rem', marginBottom: '3rem' }}><div><div style={{ width: '3rem', height: '3rem', background: 'linear-gradient(135deg, #0ea5e9, #8b5cf6)', borderRadius: '0.75rem', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white', fontWeight: 'bold', marginBottom: '1rem' }}>{content.companyName?.charAt(0) || 'L'}</div><p style={{ opacity: 0.7, lineHeight: 1.7 }}>{content.description}</p></div>{content.links.map((g: any) => <div key={g.id}><h4 style={{ fontWeight: 600, marginBottom: '1rem' }}>{g.title}</h4><ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>{g.items.map((i: any, idx: number) => <li key={idx} style={{ marginBottom: '0.75rem' }}><a href={i.url} style={{ opacity: 0.7, textDecoration: 'none', color: 'inherit' }}>{i.label}</a></li>)}</ul></div>)}</div><div style={{ borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '2rem', textAlign: 'center' }}><p style={{ opacity: 0.7, fontSize: '0.875rem' }}>{content.copyright}</p></div></div>);

const DividerSection = ({ content }: any) => <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem 0' }}><div style={{ width: '100%', height: '1px', backgroundColor: content.color }} /></div>;
const SpacerSection = ({ content }: any) => <div style={{ height: content.height }} />;

const StyleEditor = ({ section, onUpdate, onClose }: { section: Section; onUpdate: (u: Partial<Section>) => void; onClose: () => void }) => {
  const [styles, setStyles] = useState(section.styles);
  const [content, setContent] = useState(section.content);
  const updateStyles = (u: Partial<SectionStyles>) => { const n = { ...styles, ...u }; setStyles(n); onUpdate({ styles: n }); };
  const updateContent = (u: any) => { const n = { ...content, ...u }; setContent(n); onUpdate({ content: n }); };
  const pOpts = [{ v: 'none', l: 'なし' }, { v: 'small', l: '小' }, { v: 'medium', l: '中' }, { v: 'large', l: '大' }, { v: 'xlarge', l: '特大' }];
  return (
    <div style={{ position: 'fixed', right: 0, top: 0, bottom: 0, width: '300px', backgroundColor: '#1e1e2e', borderLeft: '1px solid #313244', overflowY: 'auto', zIndex: 100, padding: '1rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}><h3 style={{ color: 'white', fontWeight: 600 }}>スタイル</h3><button onClick={onClose} style={{ background: 'none', border: 'none', color: '#9ca3af', cursor: 'pointer' }}><X size={20} /></button></div>
      <div style={{ marginBottom: '1.5rem' }}><label style={{ display: 'block', color: '#9ca3af', fontSize: '0.75rem', marginBottom: '0.5rem', textTransform: 'uppercase' }}>背景</label><div style={{ display: 'flex', gap: '0.5rem' }}>{['solid', 'gradient', 'image'].map((t) => <button key={t} onClick={() => updateStyles({ backgroundType: t })} style={{ flex: 1, padding: '0.5rem', borderRadius: '0.375rem', border: 'none', cursor: 'pointer', backgroundColor: styles.backgroundType === t ? '#0ea5e9' : '#313244', color: styles.backgroundType === t ? 'white' : '#9ca3af', fontSize: '0.75rem' }}>{t === 'solid' ? '単色' : t === 'gradient' ? 'グラデ' : '画像'}</button>)}</div></div>
      {styles.backgroundType === 'solid' && <div style={{ marginBottom: '1.5rem' }}><label style={{ display: 'block', color: '#9ca3af', fontSize: '0.75rem', marginBottom: '0.5rem' }}>背景色</label><input type="color" value={styles.backgroundColor} onChange={(e) => updateStyles({ backgroundColor: e.target.value })} style={{ width: '100%', height: '40px', border: 'none', borderRadius: '0.375rem' }} /></div>}
      {styles.backgroundType === 'gradient' && <div style={{ marginBottom: '1.5rem' }}><label style={{ display: 'block', color: '#9ca3af', fontSize: '0.75rem', marginBottom: '0.5rem' }}>グラデーション</label><div style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.5rem' }}><input type="color" value={styles.gradientFrom} onChange={(e) => updateStyles({ gradientFrom: e.target.value })} style={{ flex: 1, height: '40px', border: 'none', borderRadius: '0.375rem' }} /><input type="color" value={styles.gradientTo} onChange={(e) => updateStyles({ gradientTo: e.target.value })} style={{ flex: 1, height: '40px', border: 'none', borderRadius: '0.375rem' }} /></div><select value={styles.gradientDirection} onChange={(e) => updateStyles({ gradientDirection: e.target.value })} style={{ width: '100%', padding: '0.5rem', backgroundColor: '#313244', border: 'none', borderRadius: '0.375rem', color: 'white' }}><option value="to right">左→右</option><option value="to bottom">上→下</option><option value="135deg">対角線</option></select></div>}
      {styles.backgroundType === 'image' && <ImageUploader value={styles.backgroundImage} onChange={(v) => updateStyles({ backgroundImage: v })} label="背景画像" />}
      <div style={{ marginBottom: '1.5rem' }}><label style={{ display: 'block', color: '#9ca3af', fontSize: '0.75rem', marginBottom: '0.5rem' }}>テキスト色</label><input type="color" value={styles.textColor} onChange={(e) => updateStyles({ textColor: e.target.value })} style={{ width: '100%', height: '40px', border: 'none', borderRadius: '0.375rem' }} /></div>
      <div style={{ marginBottom: '1.5rem' }}><label style={{ display: 'block', color: '#9ca3af', fontSize: '0.75rem', marginBottom: '0.5rem' }}>余白</label><div style={{ display: 'flex', gap: '0.25rem' }}>{pOpts.map((o) => <button key={o.v} onClick={() => updateStyles({ padding: o.v })} style={{ flex: 1, padding: '0.5rem', borderRadius: '0.375rem', border: 'none', cursor: 'pointer', backgroundColor: styles.padding === o.v ? '#0ea5e9' : '#313244', color: styles.padding === o.v ? 'white' : '#9ca3af', fontSize: '0.7rem' }}>{o.l}</button>)}</div></div>
      {section.type === 'hero' && <><div style={{ marginBottom: '1.5rem' }}><label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: '#9ca3af', fontSize: '0.875rem', cursor: 'pointer' }}><input type="checkbox" checked={content.overlay} onChange={(e) => updateContent({ overlay: e.target.checked })} />オーバーレイ</label>{content.overlay && <input type="range" min="0" max="1" step="0.1" value={content.overlayOpacity} onChange={(e) => updateContent({ overlayOpacity: parseFloat(e.target.value) })} style={{ width: '100%', marginTop: '0.5rem' }} />}</div><ImageUploader value={content.backgroundImage || ''} onChange={(v) => updateContent({ backgroundImage: v })} label="ヒーロー背景" /></>}
    </div>
  );
};

const TemplateSelector = ({ onSelect, onClose }: { onSelect: (k: string) => void; onClose: () => void }) => (
  <div style={{ position: 'fixed', inset: 0, backgroundColor: 'rgba(0,0,0,0.8)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 200 }}>
    <div style={{ backgroundColor: '#1e1e2e', borderRadius: '1rem', padding: '2rem', maxWidth: '600px', width: '90%' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}><h2 style={{ color: 'white', fontSize: '1.5rem', fontWeight: 'bold' }}>テンプレート</h2><button onClick={onClose} style={{ background: 'none', border: 'none', color: '#9ca3af', cursor: 'pointer' }}><X size={24} /></button></div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: '1rem' }}>{Object.entries(templates).map(([k, t]) => (<button key={k} onClick={() => { onSelect(k); onClose(); }} style={{ padding: '1.5rem', borderRadius: '0.75rem', border: '2px solid #313244', backgroundColor: 'transparent', cursor: 'pointer', textAlign: 'left' }} onMouseEnter={(e) => (e.currentTarget.style.borderColor = '#0ea5e9')} onMouseLeave={(e) => (e.currentTarget.style.borderColor = '#313244')}><div style={{ width: '3rem', height: '3rem', borderRadius: '0.75rem', backgroundColor: '#313244', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '1rem' }}><t.Icon size={24} style={{ color: '#0ea5e9' }} /></div><h3 style={{ color: 'white', fontWeight: 600, marginBottom: '0.5rem' }}>{t.name}</h3><p style={{ color: '#9ca3af', fontSize: '0.875rem' }}>{t.desc}</p></button>))}</div>
    </div>
  </div>
);

const exportToHTML = (sections: Section[], title: string) => {
  const getPad = (p: string) => ({ none: '0', small: '2rem 1rem', medium: '4rem 1rem', large: '5rem 1rem', xlarge: '6rem 1rem' }[p] || '4rem 1rem');
  const getBg = (s: SectionStyles) => s.backgroundType === 'gradient' ? `background: linear-gradient(${s.gradientDirection}, ${s.gradientFrom}, ${s.gradientTo});` : s.backgroundType === 'image' && s.backgroundImage ? `background-image: url(${s.backgroundImage}); background-size: cover;` : `background-color: ${s.backgroundColor};`;
  const render = (sec: Section): string => {
    const { type, content: c, styles: s } = sec;
    const base = `${getBg(s)} color: ${s.textColor}; padding: ${getPad(s.padding)};`;
    if (type === 'hero') return `<section style="${base} position: relative; min-height: 550px; display: flex; align-items: center; justify-content: center;">${c.overlay ? `<div style="position: absolute; inset: 0; background-color: rgba(0,0,0,${c.overlayOpacity});"></div>` : ''}<div style="position: relative; z-index: 10; max-width: 64rem; margin: 0 auto; text-align: center; padding: 2rem;"><h1 style="font-size: clamp(2.5rem, 6vw, 4rem); font-weight: bold; margin-bottom: 1.5rem; line-height: 1.1; white-space: pre-line;">${c.title}</h1><p style="font-size: clamp(1rem, 2vw, 1.5rem); opacity: 0.9; margin-bottom: 2.5rem;">${c.subtitle}</p><div style="display: flex; gap: 1rem; flex-wrap: wrap; justify-content: center;"><a href="${c.ctaLink}" style="display: inline-flex; align-items: center; gap: 0.5rem; padding: 1rem 2rem; background-color: #0ea5e9; color: white; border-radius: 0.5rem; font-size: 1.125rem; font-weight: 600; text-decoration: none;">${c.ctaText} →</a>${c.secondaryCtaText ? `<a href="${c.secondaryCtaLink}" style="display: inline-flex; padding: 1rem 2rem; background-color: transparent; color: inherit; border: 2px solid currentColor; border-radius: 0.5rem; font-weight: 600; text-decoration: none;">${c.secondaryCtaText}</a>` : ''}</div></div></section>`;
    if (type === 'features') return `<section style="${base}"><div style="max-width: 72rem; margin: 0 auto;"><div style="text-align: center; margin-bottom: 3rem;"><h2 style="font-size: 2.5rem; font-weight: bold; margin-bottom: 1rem;">${c.title}</h2><p style="opacity: 0.7;">${c.subtitle}</p></div><div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 2rem;">${c.features.map((f: any) => `<div style="text-align: center; padding: 2rem; border-radius: 1rem; background-color: rgba(14,165,233,0.05);"><div style="width: 4rem; height: 4rem; margin: 0 auto 1.5rem; background: linear-gradient(135deg, #0ea5e9, #8b5cf6); border-radius: 1rem; display: flex; align-items: center; justify-content: center; color: white; font-size: 1.5rem;">✦</div><h3 style="font-size: 1.25rem; font-weight: 600; margin-bottom: 0.75rem;">${f.title}</h3><p style="opacity: 0.7; line-height: 1.6;">${f.description}</p></div>`).join('')}</div></div></section>`;
    if (type === 'stats') return `<section style="${base}"><div style="max-width: 72rem; margin: 0 auto;"><div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 2rem;">${c.stats.map((st: any) => `<div style="text-align: center; padding: 1.5rem;"><div style="font-size: 3rem; font-weight: bold; margin-bottom: 0.5rem; background: linear-gradient(135deg, #0ea5e9, #8b5cf6); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">${st.value}</div><div style="opacity: 0.7;">${st.label}</div></div>`).join('')}</div></div></section>`;
    if (type === 'testimonials') return `<section style="${base}"><div style="max-width: 72rem; margin: 0 auto;"><div style="text-align: center; margin-bottom: 3rem;"><h2 style="font-size: 2.5rem; font-weight: bold;">${c.title}</h2></div><div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 2rem;">${c.testimonials.map((t: any) => `<div style="background-color: ${s.backgroundColor === '#ffffff' ? '#f8fafc' : 'rgba(255,255,255,0.05)'}; padding: 2rem; border-radius: 1rem;"><div style="margin-bottom: 1rem;">${'★'.repeat(t.rating)}${'☆'.repeat(5 - t.rating)}</div><p style="font-size: 1.125rem; line-height: 1.7; margin-bottom: 1.5rem;">${t.content}</p><div style="display: flex; align-items: center; gap: 1rem;"><div style="width: 3rem; height: 3rem; border-radius: 50%; background-color: #0ea5e9; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold;">${t.name.charAt(0)}</div><div><div style="font-weight: 600;">${t.name}</div><div style="font-size: 0.875rem; opacity: 0.7;">${t.role}${t.company ? ` / ${t.company}` : ''}</div></div></div></div>`).join('')}</div></div></section>`;
    if (type === 'pricing') return `<section style="${base}"><div style="max-width: 72rem; margin: 0 auto;"><div style="text-align: center; margin-bottom: 3rem;"><h2 style="font-size: 2.5rem; font-weight: bold; margin-bottom: 1rem;">${c.title}</h2><p style="opacity: 0.7;">${c.subtitle}</p></div><div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 2rem; align-items: start;">${c.plans.map((p: any) => `<div style="padding: 2.5rem; border-radius: 1.5rem; ${p.isPopular ? 'background: linear-gradient(135deg, #0ea5e9, #8b5cf6); color: white; transform: scale(1.05);' : 'background: white; border: 1px solid #e5e7eb;'}">${p.isPopular ? '<div style="position: absolute; top: -12px; left: 50%; transform: translateX(-50%); padding: 0.25rem 1rem; background-color: #fbbf24; color: #1f2937; border-radius: 9999px; font-size: 0.75rem; font-weight: 600;">人気</div>' : ''}<h3 style="font-size: 1.5rem; font-weight: bold; margin-bottom: 0.5rem;">${p.name}</h3><p style="font-size: 0.875rem; opacity: 0.8; margin-bottom: 1.5rem;">${p.description}</p><div style="margin-bottom: 2rem;"><span style="font-size: 3rem; font-weight: bold;">${p.price}</span><span style="opacity: 0.7;">${p.period}</span></div><ul style="list-style: none; padding: 0; margin-bottom: 2rem;">${p.features.map((f: string) => `<li style="display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.75rem;">✓ ${f}</li>`).join('')}</ul><button style="width: 100%; padding: 1rem; border-radius: 0.75rem; font-weight: 600; border: none; ${p.isPopular ? 'background-color: white; color: #0ea5e9;' : 'background-color: #0ea5e9; color: white;'}">${p.ctaText}</button></div>`).join('')}</div></div></section>`;
    if (type === 'faq') return `<section style="${base}"><div style="max-width: 48rem; margin: 0 auto;"><div style="text-align: center; margin-bottom: 3rem;"><h2 style="font-size: 2.5rem; font-weight: bold;">${c.title}</h2></div><div style="display: flex; flex-direction: column; gap: 1rem;">${c.items.map((item: any, i: number) => `<details ${i === 0 ? 'open' : ''} style="border: 1px solid #e5e7eb; border-radius: 1rem; overflow: hidden;"><summary style="padding: 1.5rem; cursor: pointer; font-weight: 600; font-size: 1.125rem; background: white; color: #1f2937;">${item.question}</summary><div style="padding: 0 1.5rem 1.5rem; color: #4b5563; line-height: 1.7;">${item.answer}</div></details>`).join('')}</div></div></section>`;
    if (type === 'cta') return `<section style="${base}"><div style="text-align: center; max-width: 48rem; margin: 0 auto;"><h2 style="font-size: 2.5rem; font-weight: bold; margin-bottom: 1rem;">${c.title}</h2><p style="font-size: 1.25rem; opacity: 0.9; margin-bottom: 2.5rem;">${c.subtitle}</p><div style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap;"><a href="${c.buttonLink}" style="display: inline-flex; align-items: center; gap: 0.5rem; padding: 1rem 2.5rem; background-color: white; color: #0ea5e9; border-radius: 0.5rem; font-size: 1.125rem; font-weight: 600; text-decoration: none;">${c.buttonText} →</a>${c.secondaryText ? `<a href="${c.secondaryLink}" style="display: inline-flex; padding: 1rem 2.5rem; background-color: transparent; color: white; border: 2px solid white; border-radius: 0.5rem; font-weight: 600; text-decoration: none;">${c.secondaryText}</a>` : ''}</div></div></section>`;
    if (type === 'contact') return `<section style="${base}"><div style="max-width: 40rem; margin: 0 auto;"><div style="text-align: center; margin-bottom: 3rem;"><h2 style="font-size: 2.5rem; font-weight: bold; margin-bottom: 1rem;">${c.title}</h2><p style="opacity: 0.7;">${c.subtitle}</p></div><form style="display: flex; flex-direction: column; gap: 1.5rem;">${c.fields.map((f: any) => `<div><label style="display: block; font-weight: 500; margin-bottom: 0.5rem;">${f.label}${f.required ? ' <span style="color: #ef4444;">*</span>' : ''}</label>${f.type === 'textarea' ? `<textarea placeholder="${f.placeholder}" rows="4" style="width: 100%; padding: 0.875rem; border: 2px solid #e5e7eb; border-radius: 0.75rem; resize: none; box-sizing: border-box;"></textarea>` : `<input type="${f.type}" placeholder="${f.placeholder}" style="width: 100%; padding: 0.875rem; border: 2px solid #e5e7eb; border-radius: 0.75rem; box-sizing: border-box;">`}</div>`).join('')}<button type="submit" style="padding: 1rem 2rem; background-color: #0ea5e9; color: white; border: none; border-radius: 0.75rem; font-size: 1.125rem; font-weight: 600; cursor: pointer;">${c.submitText}</button></form></div></section>`;
    if (type === 'footer') return `<footer style="${base}"><div style="max-width: 72rem; margin: 0 auto;"><div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 3rem; margin-bottom: 3rem;"><div><div style="width: 3rem; height: 3rem; background: linear-gradient(135deg, #0ea5e9, #8b5cf6); border-radius: 0.75rem; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold; margin-bottom: 1rem;">${c.companyName?.charAt(0) || 'L'}</div><p style="opacity: 0.7; line-height: 1.7;">${c.description}</p></div>${c.links.map((g: any) => `<div><h4 style="font-weight: 600; margin-bottom: 1rem;">${g.title}</h4><ul style="list-style: none; padding: 0; margin: 0;">${g.items.map((i: any) => `<li style="margin-bottom: 0.75rem;"><a href="${i.url}" style="opacity: 0.7; text-decoration: none; color: inherit;">${i.label}</a></li>`).join('')}</ul></div>`).join('')}</div><div style="border-top: 1px solid rgba(255,255,255,0.1); padding-top: 2rem; text-align: center;"><p style="opacity: 0.7; font-size: 0.875rem;">${c.copyright}</p></div></div></footer>`;
    if (type === 'logos') return `<section style="${base}"><div style="max-width: 72rem; margin: 0 auto;">${c.title ? `<h2 style="font-size: 1.25rem; font-weight: 600; margin-bottom: 2rem; text-align: center; opacity: 0.6;">${c.title}</h2>` : ''}<div style="display: flex; flex-wrap: wrap; justify-content: center; align-items: center; gap: 3rem;">${c.logos.map((l: any) => `<div style="padding: 1rem; opacity: 0.5;">${l.url ? `<img src="${l.url}" alt="${l.name}" style="height: 40px; object-fit: contain;">` : `<div style="padding: 1rem 2rem; background-color: ${s.backgroundColor === '#ffffff' ? '#f1f5f9' : 'rgba(255,255,255,0.1)'}; border-radius: 0.5rem; font-weight: 600; color: #64748b;">${l.name}</div>`}</div>`).join('')}</div></div></section>`;
    if (type === 'video') return `<section style="${base}"><div style="max-width: 56rem; margin: 0 auto;"><div style="text-align: center; margin-bottom: 2rem;"><h2 style="font-size: 2.5rem; font-weight: bold;">${c.title}</h2></div><div style="position: relative; padding-bottom: 56.25%; border-radius: 1rem; overflow: hidden; box-shadow: 0 25px 50px -12px rgba(0,0,0,0.25);"><iframe src="${c.videoUrl}" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: none;" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div></div></section>`;
    if (type === 'gallery') return `<section style="${base}"><div style="max-width: 72rem; margin: 0 auto;">${c.title ? `<div style="text-align: center; margin-bottom: 2rem;"><h2 style="font-size: 2.5rem; font-weight: bold;">${c.title}</h2></div>` : ''}<div style="display: grid; grid-template-columns: repeat(${c.columns || 3}, 1fr); gap: 1.5rem;">${c.images.map((img: any) => `<div style="aspect-ratio: 4/3; border-radius: 0.75rem; overflow: hidden; background-color: #f1f5f9;">${img.url ? `<img src="${img.url}" alt="${img.caption}" style="width: 100%; height: 100%; object-fit: cover;">` : `<div style="width: 100%; height: 100%; display: flex; align-items: center; justify-content: center; color: #94a3b8;">${img.caption}</div>`}</div>`).join('')}</div></div></section>`;
    if (type === 'divider') return `<div style="padding: 1rem 0;"><div style="width: 100%; height: 1px; background-color: ${c.color};"></div></div>`;
    if (type === 'spacer') return `<div style="height: ${c.height}px;"></div>`;
    return '';
  };
  const html = `<!DOCTYPE html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${title}</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+JP:wght@400;500;700&display=swap" rel="stylesheet"><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Noto Sans JP','Inter',sans-serif;line-height:1.6}img{max-width:100%;height:auto}a{transition:opacity 0.2s}a:hover{opacity:0.8}button{transition:transform 0.2s}button:hover{transform:translateY(-2px)}details>summary{list-style:none}details>summary::-webkit-details-marker{display:none}</style></head><body>${sections.map(render).join('')}</body></html>`;
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = `${title.toLowerCase().replace(/\s+/g, '-')}.html`; a.click();
  URL.revokeObjectURL(url);
};

export default function App() {
  const [sections, setSections] = useState<Section[]>([{ id: '1', type: 'hero', content: getDefaultContent('hero'), styles: getDefaultStyles('hero') }]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [mode, setMode] = useState<'edit' | 'preview'>('edit');
  const [device, setDevice] = useState<'desktop' | 'tablet' | 'mobile'>('desktop');
  const [showStyleEditor, setShowStyleEditor] = useState(false);
  const [showTemplates, setShowTemplates] = useState(false);
  const [pageTitle, setPageTitle] = useState('My Landing Page');

  const addSection = (type: SectionType) => setSections([...sections, { id: Date.now().toString(), type, content: getDefaultContent(type), styles: getDefaultStyles(type) }]);
  const deleteSection = (id: string) => { setSections(sections.filter(s => s.id !== id)); if (selectedId === id) { setSelectedId(null); setShowStyleEditor(false); } };
  const duplicateSection = (id: string) => { const idx = sections.findIndex(s => s.id === id); if (idx !== -1) { const n = { ...JSON.parse(JSON.stringify(sections[idx])), id: Date.now().toString() }; const arr = [...sections]; arr.splice(idx + 1, 0, n); setSections(arr); } };
  const moveSection = (id: string, dir: 'up' | 'down') => { const idx = sections.findIndex(s => s.id === id); if ((dir === 'up' && idx > 0) || (dir === 'down' && idx < sections.length - 1)) { const arr = [...sections]; const t = dir === 'up' ? idx - 1 : idx + 1; [arr[idx], arr[t]] = [arr[t], arr[idx]]; setSections(arr); } };
  const updateSection = (id: string, u: Partial<Section>) => setSections(sections.map(s => s.id === id ? { ...s, ...u } : s));
  const loadTemplate = (k: string) => { const t = templates[k]; if (t) setSections(t.sections.map(s => ({ ...s, id: Date.now().toString() + Math.random() }))); };

  const selectedSection = sections.find(s => s.id === selectedId);
  const getPad = (p: string) => ({ none: '0', small: '2rem 1rem', medium: '4rem 1rem', large: '5rem 1rem', xlarge: '6rem 1rem' }[p] || '4rem 1rem');
  const getBgStyle = (s: SectionStyles): React.CSSProperties => s.backgroundType === 'gradient' ? { background: `linear-gradient(${s.gradientDirection}, ${s.gradientFrom}, ${s.gradientTo})` } : s.backgroundType === 'image' && s.backgroundImage ? { backgroundImage: `url(${s.backgroundImage})`, backgroundSize: 'cover', backgroundPosition: 'center' } : { backgroundColor: s.backgroundColor };

  const renderSection = (sec: Section) => {
    const props = { content: sec.content, styles: sec.styles, isPreview: mode === 'preview', onUpdate: (c: any) => updateSection(sec.id, { content: c }) };
    const comps: Record<SectionType, any> = { hero: HeroSection, features: FeaturesSection, pricing: PricingSection, testimonials: TestimonialsSection, stats: StatsSection, video: VideoSection, gallery: GallerySection, logos: LogosSection, faq: FAQSection, cta: CTASection, contact: ContactSection, footer: FooterSection, divider: DividerSection, spacer: SpacerSection };
    const C = comps[sec.type]; return C ? <C {...props} /> : null;
  };

  const deviceWidths = { desktop: '100%', tablet: '768px', mobile: '375px' };

  return (
    <div className="h-screen flex flex-col bg-slate-900 font-sans">
      {showTemplates && <TemplateSelector onSelect={loadTemplate} onClose={() => setShowTemplates(false)} />}
      <header className="h-14 flex items-center justify-between px-4 bg-slate-800 border-b border-slate-700">
        <div className="flex items-center gap-3"><div className="w-8 h-8 bg-gradient-to-br from-sky-500 to-violet-600 rounded-lg flex items-center justify-center text-white font-bold text-sm">LP</div><span className="text-slate-200 font-semibold">LP Builder Pro</span></div>
        <div className="flex items-center gap-2">
          <button onClick={() => setShowTemplates(true)} className="flex items-center gap-2 px-3 py-1.5 bg-slate-700 text-slate-300 rounded-lg hover:bg-slate-600 text-sm"><FolderOpen size={16} />テンプレート</button>
          <div className="flex bg-slate-900 rounded-lg p-1 ml-2">{([{ t: 'desktop', I: Monitor }, { t: 'tablet', I: Tablet }, { t: 'mobile', I: Smartphone }] as const).map(({ t, I }) => <button key={t} onClick={() => setDevice(t)} className={`p-2 rounded-md ${device === t ? 'bg-sky-600 text-white' : 'text-slate-400 hover:bg-slate-700'}`}><I size={18} /></button>)}</div>
          <div className="flex bg-slate-900 rounded-lg p-1 ml-2"><button onClick={() => setMode('edit')} className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm ${mode === 'edit' ? 'bg-sky-600 text-white' : 'text-slate-400 hover:bg-slate-700'}`}><Pencil size={16} />編集</button><button onClick={() => setMode('preview')} className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm ${mode === 'preview' ? 'bg-sky-600 text-white' : 'text-slate-400 hover:bg-slate-700'}`}><Eye size={16} />プレビュー</button></div>
        </div>
        <button onClick={() => exportToHTML(sections, pageTitle)} className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-sky-600 to-violet-600 text-white rounded-lg font-semibold hover:opacity-90"><Download size={18} />エクスポート</button>
      </header>
      <div className="flex flex-1 overflow-hidden">
        {mode === 'edit' && (
          <aside className="w-64 bg-slate-800 border-r border-slate-700 overflow-y-auto">
            <div className="p-4"><p className="text-xs text-slate-500 mb-3 uppercase tracking-wider">セクション追加</p><div className="grid grid-cols-2 gap-1">{(Object.keys(sectionMeta) as SectionType[]).map((type) => { const { label, Icon } = sectionMeta[type]; return <button key={type} onClick={() => addSection(type)} className="flex flex-col items-center gap-1 p-2 rounded-lg text-slate-400 hover:bg-slate-700 hover:text-white text-xs"><Icon size={18} />{label}</button>; })}</div></div>
            <div className="border-t border-slate-700 p-4"><p className="text-xs text-slate-500 mb-3 uppercase tracking-wider">レイヤー</p>{sections.map((sec, idx) => { const { Icon } = sectionMeta[sec.type] || { Icon: Layers }; return (<div key={sec.id} onClick={() => { setSelectedId(sec.id); setShowStyleEditor(true); }} className={`flex items-center gap-2 p-2 rounded-lg cursor-pointer mb-1 ${selectedId === sec.id ? 'bg-sky-600/20 ring-1 ring-sky-500' : 'hover:bg-slate-700'}`}><Icon size={14} className="text-slate-400" /><span className="flex-1 text-sm text-slate-300 truncate">{sectionMeta[sec.type]?.label}</span><div className="flex gap-0.5"><button onClick={(e) => { e.stopPropagation(); moveSection(sec.id, 'up'); }} className="p-1 hover:bg-slate-600 rounded" disabled={idx === 0}><ChevronUp size={12} className="text-slate-400" /></button><button onClick={(e) => { e.stopPropagation(); moveSection(sec.id, 'down'); }} className="p-1 hover:bg-slate-600 rounded" disabled={idx === sections.length - 1}><ChevronDown size={12} className="text-slate-400" /></button></div></div>); })}</div>
            <div className="border-t border-slate-700 p-4"><p className="text-xs text-slate-500 mb-2 uppercase tracking-wider">ページタイトル</p><input type="text" value={pageTitle} onChange={(e) => setPageTitle(e.target.value)} className="w-full px-3 py-2 bg-slate-900 border border-slate-600 rounded-lg text-white text-sm" /></div>
          </aside>
        )}
        <main className="flex-1 overflow-auto p-6 bg-slate-950/50" style={{ backgroundImage: 'radial-gradient(circle at 1px 1px, rgba(255,255,255,0.05) 1px, transparent 0)', backgroundSize: '20px 20px' }}>
          <div className="mx-auto bg-white min-h-full shadow-2xl transition-all duration-300 overflow-hidden" style={{ maxWidth: deviceWidths[device] }}>
            {sections.length === 0 ? (<div className="flex flex-col items-center justify-center h-96 text-gray-400"><Layers size={48} className="mb-4 text-sky-500" /><p className="text-lg font-medium mb-2">セクションがありません</p><p className="text-sm mb-4">左からセクションを追加</p><button onClick={() => setShowTemplates(true)} className="px-4 py-2 bg-sky-600 text-white rounded-lg text-sm">テンプレート</button></div>) : (
              sections.map(sec => (<div key={sec.id} className="relative group" onClick={() => mode === 'edit' && setSelectedId(sec.id)}>{mode === 'edit' && (<div className="absolute left-2 top-2 z-20 flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity"><button onClick={(e) => { e.stopPropagation(); setSelectedId(sec.id); setShowStyleEditor(true); }} className="p-2 bg-white rounded-lg shadow-lg hover:bg-gray-50" title="スタイル"><Palette size={16} className="text-gray-600" /></button><button onClick={(e) => { e.stopPropagation(); duplicateSection(sec.id); }} className="p-2 bg-white rounded-lg shadow-lg hover:bg-gray-50" title="複製"><Copy size={16} className="text-gray-600" /></button><button onClick={(e) => { e.stopPropagation(); deleteSection(sec.id); }} className="p-2 bg-white rounded-lg shadow-lg hover:bg-red-50" title="削除"><Trash2 size={16} className="text-red-500" /></button></div>)}<div className={selectedId === sec.id && mode === 'edit' ? 'ring-2 ring-sky-500 ring-inset' : ''} style={{ ...getBgStyle(sec.styles), color: sec.styles.textColor, padding: getPad(sec.styles.padding) }}>{renderSection(sec)}</div></div>))
            )}
          </div>
        </main>
        {showStyleEditor && selectedSection && mode === 'edit' && <StyleEditor section={selectedSection} onUpdate={(u) => updateSection(selectedId!, u)} onClose={() => setShowStyleEditor(false)} />}
      </div>
    </div>
  );
}
